### ISSUE TITLE
Feature request: Reporting on log scale for changes in lux

### ISSUE THREAD

**Issue by rakgupta** [HubitatCommunity/AeotecMultiSensor6#2]
Hi - any chance you could add reporting based on lux changes on a log scale (like the HE driver for Philips Outdoor Motion sensor) for the MS 6?
<img width="387" alt="Screen Shot 2021-04-05 at 6 58 43 PM" src="https://user-images.githubusercontent.com/59174606/113640517-3f103700-9641-11eb-9ffb-29484e92ee09.png">

The use case is that at the lower end of the scale the changes are more relevant for lighting control than at the high end (my threshold is between 20-30, < 20 turn lights on, > 30 turn lights off). Thanks!

EDIT: My sensor is located indoors - on a sunny day like today, the range of lux readings were 0-145

**Comment by csteele-PD** [comment]
The values are generated within the Aeon Multisensor 6. You would need to submit your request to Aeon/Aeotec.
